In [1]:
import pandas as pd
import numpy as np
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
path = '/content/drive/MyDrive/Colab Notebooks/wine.csv'

In [5]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [11]:
from sklearn.model_selection import train_test_split

# CSV 파일을 읽어서 데이터로 가져오기
df = pd.read_csv(path)

# 데이터 전체 보기
df

# 'Wine' 열(정답)을 제외한 나머지 컬럼들
x=df.drop('Wine',axis=1)
# 'Wine' 열만 따로 가져옴
y=df['Wine']
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.25,random_state=0)

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)

# 모델 학습
clf_lr.fit(x_train, y_train)

# 예측
pred_lr = clf_lr.predict(x_test)

# 정확도 출력
print(accuracy_score(y_test, pred_lr))

# 혼동행렬 출력
print(confusion_matrix(y_test, pred_lr))

0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Decision Tree

In [17]:
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


# Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)

pred = rf_clf.predict(x_test)

print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]


# KNN

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
from sklearn import metrics

scores = metrics.accuracy_score(y_test, y_pred)
print(scores)

0.7333333333333333
